spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:changeme
    username: sa
  jpa:
    database: h2
    show-sql: true
    properties:
      hibernate:
        dialect : org.hibernate.dialect.H2Dialect